spring.application.name=server
# Database configuration for MySQL (replace with your database details)
spring.datasource.url=jdbc:mysql://localhost:3308/quicktix
spring.datasource.username=root
spring.datasource.password=taprodb321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT Configuration
app.jwt.secret=GjYj9AKj1Z3*pD8^d!Lk2KwW5XyN3RbPzQ
app.jwt.expirationMs=3600000